spring:
  application:
    name: auth-api
  profiles:
    active: dev
  config:
    import:
      - 'nacos:auth-dev.yaml?group=common'
      - 'nacos:auth-service-dev.yaml?group=sunflower_class'
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        namespace: ${NACOS_NAMESPACE:dev}
        group: sunflower_class
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        namespace: ${NACOS_NAMESPACE:dev}
        group: sunflower_class

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
