# server:
#   servlet:
#     context-path: /content
#   port: 63040

# 微服务配置
spring:
  application:
    name: content-api
  profiles:
    active: dev
  config:
    import:
      - "nacos:content-service-dev.yaml?group=sunflower_class"
      - "nacos:content-api-dev.yaml?group=sunflower_class"
      - "nacos:logging-dev.yaml?group=common"
      - "nacos:swagger-dev.yaml?group=common"
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 172.24.77.139:8848
        namespace: dev
        group: sunflower_class
        file-extension: yaml
        refresh-enabled: true
      discovery:
        enabled: true
        server-addr: 172.24.77.139:8848
        namespace: dev
        group: sunflower_class
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://172.24.77.139:3306/sunflower_class?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
#     username: root
#     password: Cjlei520..

# # Swagger 配置
# springdoc:
#   api-docs:
#     path: /v3/api-docs
#   swagger-ui:
#     path: /swagger-ui.html
#     tags-sorter: alpha
#     operations-sorter: alpha
#   packages-to-scan: com.sunflower_class.api

# # Knife4j 配置
# knife4j:
#   enable: ${SWAGGER_ENABLED:true}
#   setting:
#     language: zh-CN

# 日志文件配置路径
logging:
  level:
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG
  config: classpath:logback.xml