
spring:
  application:
    name: content-api
  profiles:
    active: dev
  config:
    import:
      - "nacos:content-service-dev.yaml?group=sunflower_class"
      - "nacos:content-api-dev.yaml?group=sunflower_class"
      - "nacos:logging-dev.yaml?group=common"
      - "nacos:swagger-dev.yaml?group=common"
      - "nacos:rabbitmq-dev.yaml?group=common"
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: sunflower_class
        file-extension: yaml
        refresh-enabled: true
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: sunflower_class



logging:
  level:
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG
  config: classpath:logback.xml

sunflower:
  company-id: ${SUNFLOWER_COMPANY_ID:1232141425}
